<h2 style="color:green" align="center">Implement Neural Network (or Logistic Regression) From Scratch</h2>

<h4 style="color:blue">Predicting if a person would buy life insurnace based on his age using logistic regression</h4>

Above is a binary logistic regression problem as there are only two possible outcomes (i.e. if person buys insurance or he/she doesn't).

In [4]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [5]:
df = pd.read_csv("insurance_data.csv")
df.head()

   age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

**Split train and test set**

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2, random_state=25)

**Preprocessing: Scale the data so that both age and affordibility are in same scaling range**

In [9]:
X_train_scaled = X_train.copy()
X_train_scaled['age'] = X_train_scaled['age'] / 100

X_test_scaled = X_test.copy()
X_test_scaled['age'] = X_test_scaled['age'] / 100

**Model Building: First build a model in keras/tensorflow and see what weights and bias values it comes up with. We will than try to reproduce same weights and bias in our plain python implementation of gradient descent. Below is the architecture of our simple neural network**

<img src="nn.jpg" height=800 width=800/>

In [12]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,), activation='sigmoid', kernel_initializer='ones', bias_initializer='zeros')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train_scaled, y_train, epochs=50)

C:\Users\Admin\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Epoch 1/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.5000 - loss: 0.7113
Epoch 2/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7110
Epoch 3/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7106
Epoch 4/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 194ms/step - accuracy: 0.5000 - loss: 0.7102
Epoch 5/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.5000 - loss: 0.7098
Epoch 6/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.5000 - loss: 0.7094
Epoch 7/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.5000 - loss: 0.7091
Epoch 8/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.5000 - loss: 0.7087
Epoch 9/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.7083
Epoch 10/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.7079
Epoch 11/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5000 - loss: 0.7076
Epoch 12/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.5000 - loss: 0.7072
Epoch 13/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.5000 - loss: 0.7068
Epoch 14/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5000 - loss: 0.7065
Epoch 15/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 161ms/step - accuracy: 0.5000 - loss: 0.7061
Epoch 16/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - accuracy: 0.5000 - loss: 0.7057
Epoch 17/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.5000 - loss: 0.7054
Epoch 18/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5000 - loss: 0.7050
Epoch 19/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - accuracy: 0.5000 - loss: 0.7046
Epoch 20/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - accuracy: 0.5000 - loss: 0.7043
Epoch 21/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - accuracy: 0.5000 - loss: 0.7039
Epoch 22/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.5000 - loss: 0.7035
Epoch 23/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.5000 - loss: 0.7032
Epoch 24/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.7028
Epoch 25/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.5000 - loss: 0.7025
Epoch 26/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.5000 - loss: 0.7021
Epoch 27/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.5000 - loss: 0.7017
Epoch 28/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.5000 - loss: 0.7014
Epoch 29/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.5000 - loss: 0.7010
Epoch 30/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.5000 - loss: 0.7007
Epoch 31/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.7003
Epoch 32/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.7000
Epoch 33/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - accuracy: 0.5000 - loss: 0.6996
Epoch 34/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.5000 - loss: 0.6993
Epoch 35/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - accuracy: 0.5000 - loss: 0.6989
Epoch 36/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.5000 - loss: 0.6986
Epoch 37/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.5000 - loss: 0.6982
Epoch 38/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.5000 - loss: 0.6979
Epoch 39/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.6975
Epoch 40/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.5000 - loss: 0.6972
Epoch 41/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.5000 - loss: 0.6969
Epoch 42/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.5000 - loss: 0.6965
Epoch 43/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5000 - loss: 0.6962
Epoch 44/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 158ms/step - accuracy: 0.5000 - loss: 0.6958
Epoch 45/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.5000 - loss: 0.6955
Epoch 46/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.5000 - loss: 0.6952
Epoch 47/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.5000 - loss: 0.6948
Epoch 48/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.5000 - loss: 0.6945
Epoch 49/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.5000 - loss: 0.6942
Epoch 50/50
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.5000 - loss: 0.6938

Epoch 247/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6479 - accuracy: 0.5909
Epoch 248/5000
1/1 [==============================] - 0s 3ms/step - loss: 0.6477 - accuracy: 0.5909
Epoch 249/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6476 - accuracy: 0.5909
Epoch 250/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6474 - accuracy: 0.5909
Epoch 251/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6473 - accuracy: 0.5909
Epoch 252/5000
1/1 [==============================] - 0s 5ms/step - loss: 0.6471 - accuracy: 0.5909
Epoch 253/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6470 - accuracy: 0.5909
Epoch 254/5000
1/1 [==============================] - 0s 0s/step - loss: 0.6468 - accuracy: 0.5909
Epoch 255/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6467 - accuracy: 0.5909
Epoch 256/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6465 - accuracy: 0.5909
Epoch 257/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6464 - accuracy: 0.5909
Epoch 258/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6463 - accuracy: 0.5909
Epoch 259/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6461 - accuracy: 0.6364
Epoch 260/5000
1/1 [==============================] - 0s 1000us/step - loss: 0.6460 - accuracy: 0.6364
Epoch 261/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6458 - accuracy: 0.6364
Epoch 262/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6457 - accuracy: 0.6364
Epoch 263/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6456 - accuracy: 0.6364
Epoch 264/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6454 - accuracy: 0.6364
Epoch 265/5000
1/1 [==============================] - ETA: 0s - loss: 0.6453 - accuracy: 0.63 - 0s 3ms/step - loss: 0.6453 - accuracy: 0.6364
Epoch 266/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6452 - accuracy: 0.6364
Epoch 267/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6450 - accuracy: 0.6364
Epoch 268/5000
1/1 [==============================] - 0s 997us/step - loss: 0.6449 - accuracy: 0.6364
Epoch 269/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6448 - accuracy: 0.6364
Epoch 270/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6446 - accuracy: 0.6364
Epoch 271/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6445 - accuracy: 0.6364
Epoch 272/5000
1/1 [==============================] - 0s 751us/step - loss: 0.6444 - accuracy: 0.6364
Epoch 273/5000
1/1 [==============================] - 0s 0s/step - loss: 0.6442 - accuracy: 0.6364
Epoch 274/5000
1/1 [==============================] - 0s 996us/step - loss: 0.6441 - accuracy: 0.6364
Epoch 275/5000
1/1 [==============================] - 0s 998us/step - loss: 0.6440 - accuracy: 0.6364
Epoch 276/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6438 - accuracy: 0.6364
Epoch 277/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6437 - accuracy: 0.6364
Epoch 278/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6436 - accuracy: 0.6364
Epoch 279/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6435 - accuracy: 0.6364
Epoch 280/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6433 - accuracy: 0.6364
Epoch 281/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6432 - accuracy: 0.6364
Epoch 282/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6431 - accuracy: 0.6364
Epoch 283/5000
1/1 [==============================] - 0s 1000us/step - loss: 0.6430 - accuracy: 0.6364
Epoch 284/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6428 - accuracy: 0.6364
Epoch 285/5000
1/1 [==============================] - 0s 0s/step - loss: 0.6427 - accuracy: 0.6364
Epoch 286/5000
1/1 [==============================] - 0s 0s/step - loss: 0.6426 - accuracy: 0.6364
Epoch 287/5000
1/1 [==============================] - 0s 0s/step - loss: 0.6425 - accuracy: 0.6364
Epoch 288/5000
1/1 [==============================] - 0s 1000us/step - loss: 0.6423 - accuracy: 0.6364
Epoch 289/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6422 - accuracy: 0.6364
Epoch 290/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6421 - accuracy: 0.6364
Epoch 291/5000
1/1 [==============================] - 0s 0s/step - loss: 0.6420 - accuracy: 0.6364
Epoch 292/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6419 - accuracy: 0.6364
Epoch 293/5000
1/1 [==============================] - 0s 3ms/step - loss: 0.6417 - accuracy: 0.6364
Epoch 294/5000
1/1 [==============================] - 0s 1000us/step - loss: 0.6416 - accuracy: 0.6364
Epoch 295/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6415 - accuracy: 0.6364
Epoch 296/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6414 - accuracy: 0.6364
Epoch 297/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6413 - accuracy: 0.6364
Epoch 298/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6411 - accuracy: 0.6364
Epoch 299/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6410 - accuracy: 0.6364
Epoch 300/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6409 - accuracy: 0.6364
Epoch 301/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6408 - accuracy: 0.6364
Epoch 302/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6407 - accuracy: 0.6364
Epoch 303/5000
1/1 [==============================] - 0s 1000us/step - loss: 0.6406 - accuracy: 0.6364
Epoch 304/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6405 - accuracy: 0.6364
Epoch 305/5000
1/1 [==============================] - 0s 975us/step - loss: 0.6403 - accuracy: 0.6364
Epoch 306/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6402 - accuracy: 0.6364
Epoch 307/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6401 - accuracy: 0.6364
Epoch 308/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6400 - accuracy: 0.6364
Epoch 309/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6399 - accuracy: 0.6364
Epoch 310/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6398 - accuracy: 0.6364
Epoch 311/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6397 - accuracy: 0.6364
Epoch 312/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6396 - accuracy: 0.6364
Epoch 313/5000
1/1 [==============================] - 0s 4ms/step - loss: 0.6395 - accuracy: 0.6364
Epoch 314/5000
1/1 [==============================] - 0s 0s/step - loss: 0.6394 - accuracy: 0.6364
Epoch 315/5000
1/1 [==============================] - 0s 911us/step - loss: 0.6392 - accuracy: 0.6364
Epoch 316/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6391 - accuracy: 0.6364
Epoch 317/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6390 - accuracy: 0.6364
Epoch 318/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6389 - accuracy: 0.6364
Epoch 319/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6388 - accuracy: 0.6364
Epoch 320/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6387 - accuracy: 0.6364
Epoch 321/5000
1/1 [==============================] - 0s 4ms/step - loss: 0.6386 - accuracy: 0.6364
Epoch 322/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6385 - accuracy: 0.6364
Epoch 323/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6384 - accuracy: 0.6364
Epoch 324/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6383 - accuracy: 0.6364
Epoch 325/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6382 - accuracy: 0.6364
Epoch 326/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6381 - accuracy: 0.6364
Epoch 327/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6380 - accuracy: 0.6364
Epoch 328/5000

1/1 [==============================] - 0s 1ms/step - loss: 0.6379 - accuracy: 0.6364
Epoch 329/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6378 - accuracy: 0.6364
Epoch 330/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6377 - accuracy: 0.6364
Epoch 331/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6376 - accuracy: 0.6364
Epoch 332/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6375 - accuracy: 0.6364
Epoch 333/5000
1/1 [==============================] - 0s 0s/step - loss: 0.6374 - accuracy: 0.6364
Epoch 334/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6373 - accuracy: 0.6364
Epoch 335/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6372 - accuracy: 0.6364
Epoch 336/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6371 - accuracy: 0.6364
Epoch 337/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6370 - accuracy: 0.6364
Epoch 338/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6369 - accuracy: 0.6364
Epoch 339/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6368 - accuracy: 0.6364
Epoch 340/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6367 - accuracy: 0.6364
Epoch 341/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6366 - accuracy: 0.6364
Epoch 342/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6365 - accuracy: 0.6364
Epoch 343/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6364 - accuracy: 0.6364
Epoch 344/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6363 - accuracy: 0.6364
Epoch 345/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6362 - accuracy: 0.6364
Epoch 346/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6361 - accuracy: 0.6364
Epoch 347/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6361 - accuracy: 0.6364
Epoch 348/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6360 - accuracy: 0.6364
Epoch 349/5000
1/1 [==============================] - 0s 3ms/step - loss: 0.6359 - accuracy: 0.6364
Epoch 350/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6358 - accuracy: 0.6364
Epoch 351/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6357 - accuracy: 0.6364
Epoch 352/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6356 - accuracy: 0.6364
Epoch 353/5000
1/1 [==============================] - 0s 4ms/step - loss: 0.6355 - accuracy: 0.6364
Epoch 354/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6354 - accuracy: 0.6364
Epoch 355/5000
1/1 [==============================] - 0s 1000us/step - loss: 0.6353 - accuracy: 0.6364
Epoch 356/5000
1/1 [==============================] - 0s 1000us/step - loss: 0.6352 - accuracy: 0.6364
Epoch 357/5000
1/1 [==============================] - 0s 999us/step - loss: 0.6352 - accuracy: 0.6364
Epoch 358/5000
1/1 [==============================] - 0s 4ms/step - loss: 0.6351 - accuracy: 0.6364
Epoch 359/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6350 - accuracy: 0.6364
Epoch 360/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6349 - accuracy: 0.6364
Epoch 361/5000
1/1 [==============================] - 0s 0s/step - loss: 0.6348 - accuracy: 0.6364
Epoch 362/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6347 - accuracy: 0.6364
Epoch 363/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6346 - accuracy: 0.6364
Epoch 364/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6345 - accuracy: 0.6364
Epoch 365/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6345 - accuracy: 0.6364
Epoch 366/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6344 - accuracy: 0.6364
Epoch 367/5000
1/1 [==============================] - 0s 1000us/step - loss: 0.6343 - accuracy: 0.6364
Epoch 368/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6342 - accuracy: 0.6364
Epoch 369/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6341 - accuracy: 0.6364
Epoch 370/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6340 - accuracy: 0.6364
Epoch 371/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6339 - accuracy: 0.6364
Epoch 372/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6339 - accuracy: 0.6364
Epoch 373/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6338 - accuracy: 0.6364
Epoch 374/5000
1/1 [==============================] - 0s 0s/step - loss: 0.6337 - accuracy: 0.6364
Epoch 375/5000
1/1 [==============================] - 0s 0s/step - loss: 0.6336 - accuracy: 0.6364
Epoch 376/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6335 - accuracy: 0.6364
Epoch 377/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6335 - accuracy: 0.6364
Epoch 378/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6334 - accuracy: 0.6364
Epoch 379/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6333 - accuracy: 0.6364
Epoch 380/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6332 - accuracy: 0.6364
Epoch 381/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6331 - accuracy: 0.6364
Epoch 382/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6331 - accuracy: 0.6364
Epoch 383/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6330 - accuracy: 0.6364
Epoch 384/5000
1/1 [==============================] - 0s 999us/step - loss: 0.6329 - accuracy: 0.6364
Epoch 385/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6328 - accuracy: 0.6364
Epoch 386/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6327 - accuracy: 0.6364
Epoch 387/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6327 - accuracy: 0.6364
Epoch 388/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6326 - accuracy: 0.6364
Epoch 389/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6325 - accuracy: 0.6364
Epoch 390/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6324 - accuracy: 0.6364
Epoch 391/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6323 - accuracy: 0.6364
Epoch 392/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6323 - accuracy: 0.6364
Epoch 393/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6322 - accuracy: 0.6364
Epoch 394/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6321 - accuracy: 0.6364
Epoch 395/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6320 - accuracy: 0.6364
Epoch 396/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6320 - accuracy: 0.6364
Epoch 397/5000
1/1 [==============================] - 0s 0s/step - loss: 0.6319 - accuracy: 0.6364
Epoch 398/5000
1/1 [==============================] - 0s 0s/step - loss: 0.6318 - accuracy: 0.6364
Epoch 399/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6317 - accuracy: 0.6364
Epoch 400/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6317 - accuracy: 0.6364
Epoch 401/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6316 - accuracy: 0.6364
Epoch 402/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6315 - accuracy: 0.6364
Epoch 403/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6314 - accuracy: 0.6364
Epoch 404/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6314 - accuracy: 0.6364
Epoch 405/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6313 - accuracy: 0.6364
Epoch 406/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6312 - accuracy: 0.6364
Epoch 407/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6312 - accuracy: 0.6364
Epoch 408/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6311 - accuracy: 0.6364
Epoch 409/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6310 - accuracy: 0.6364
Epoch 410/5000

1/1 [==============================] - 0s 1ms/step - loss: 0.6309 - accuracy: 0.6364
Epoch 411/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6309 - accuracy: 0.6364
Epoch 412/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6308 - accuracy: 0.6364
Epoch 413/5000
1/1 [==============================] - 0s 0s/step - loss: 0.6307 - accuracy: 0.6364
Epoch 414/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6307 - accuracy: 0.6364
Epoch 415/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6306 - accuracy: 0.6364
Epoch 416/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6305 - accuracy: 0.6364
Epoch 417/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6305 - accuracy: 0.6364
Epoch 418/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6304 - accuracy: 0.6364
Epoch 419/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6303 - accuracy: 0.6364
Epoch 420/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6302 - accuracy: 0.6364
Epoch 421/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6302 - accuracy: 0.6364
Epoch 422/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6301 - accuracy: 0.6364
Epoch 423/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6300 - accuracy: 0.6364
Epoch 424/5000
1/1 [==============================] - 0s 3ms/step - loss: 0.6300 - accuracy: 0.6364
Epoch 425/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6299 - accuracy: 0.6364
Epoch 426/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6298 - accuracy: 0.6364
Epoch 427/5000
1/1 [==============================] - 0s 4ms/step - loss: 0.6298 - accuracy: 0.6364
Epoch 428/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6297 - accuracy: 0.6364
Epoch 429/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6296 - accuracy: 0.6364
Epoch 430/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6296 - accuracy: 0.6364
Epoch 431/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6295 - accuracy: 0.6364
Epoch 432/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6294 - accuracy: 0.6364
Epoch 433/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6294 - accuracy: 0.6364
Epoch 434/5000
1/1 [==============================] - 0s 3ms/step - loss: 0.6293 - accuracy: 0.6364
Epoch 435/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6292 - accuracy: 0.6364
Epoch 436/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6292 - accuracy: 0.6364
Epoch 437/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6291 - accuracy: 0.6364
Epoch 438/5000
1/1 [==============================] - 0s 3ms/step - loss: 0.6290 - accuracy: 0.6364
Epoch 439/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6290 - accuracy: 0.6364
Epoch 440/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6289 - accuracy: 0.6364
Epoch 441/5000
1/1 [==============================] - 0s 3ms/step - loss: 0.6288 - accuracy: 0.6364
Epoch 442/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6288 - accuracy: 0.6364
Epoch 443/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6287 - accuracy: 0.6364
Epoch 444/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6287 - accuracy: 0.6364
Epoch 445/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6286 - accuracy: 0.6364
Epoch 446/5000
1/1 [==============================] - 0s 0s/step - loss: 0.6285 - accuracy: 0.6364
Epoch 447/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6285 - accuracy: 0.6364
Epoch 448/5000
1/1 [==============================] - 0s 3ms/step - loss: 0.6284 - accuracy: 0.6364
Epoch 449/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6283 - accuracy: 0.6364
Epoch 450/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6283 - accuracy: 0.6364
Epoch 451/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6282 - accuracy: 0.6364
Epoch 452/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6282 - accuracy: 0.6364
Epoch 453/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6281 - accuracy: 0.6364
Epoch 454/5000
1/1 [==============================] - 0s 3ms/step - loss: 0.6280 - accuracy: 0.6364
Epoch 455/5000
1/1 [==============================] - 0s 1000us/step - loss: 0.6280 - accuracy: 0.6364
Epoch 456/5000
1/1 [==============================] - 0s 1000us/step - loss: 0.6279 - accuracy: 0.6364
Epoch 457/5000
1/1 [==============================] - 0s 1000us/step - loss: 0.6278 - accuracy: 0.6364
Epoch 458/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6278 - accuracy: 0.6364
Epoch 459/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6277 - accuracy: 0.6364
Epoch 460/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6277 - accuracy: 0.6364
Epoch 461/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6276 - accuracy: 0.6364
Epoch 462/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6275 - accuracy: 0.6364
Epoch 463/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6275 - accuracy: 0.6364
Epoch 464/5000
1/1 [==============================] - 0s 999us/step - loss: 0.6274 - accuracy: 0.6364
Epoch 465/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6274 - accuracy: 0.6364
Epoch 466/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6273 - accuracy: 0.6364
Epoch 467/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6272 - accuracy: 0.6364
Epoch 468/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6272 - accuracy: 0.6364
Epoch 469/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6271 - accuracy: 0.6364
Epoch 470/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6271 - accuracy: 0.6364
Epoch 471/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6270 - accuracy: 0.6364
Epoch 472/5000
1/1 [==============================] - 0s 1000us/step - loss: 0.6269 - accuracy: 0.6364
Epoch 473/5000
1/1 [==============================] - 0s 1000us/step - loss: 0.6269 - accuracy: 0.6364
Epoch 474/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6268 - accuracy: 0.6364
Epoch 475/5000
1/1 [==============================] - 0s 0s/step - loss: 0.6268 - accuracy: 0.6364
Epoch 476/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6267 - accuracy: 0.6364
Epoch 477/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6267 - accuracy: 0.6364
Epoch 478/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6266 - accuracy: 0.6364
Epoch 479/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6265 - accuracy: 0.6364
Epoch 480/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6265 - accuracy: 0.6364
Epoch 481/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6264 - accuracy: 0.6364
Epoch 482/5000
1/1 [==============================] - 0s 504us/step - loss: 0.6264 - accuracy: 0.6364
Epoch 483/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6263 - accuracy: 0.6364
Epoch 484/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6262 - accuracy: 0.6364
Epoch 485/5000
1/1 [==============================] - 0s 999us/step - loss: 0.6262 - accuracy: 0.6364
Epoch 486/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6261 - accuracy: 0.6364
Epoch 487/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6261 - accuracy: 0.6364
Epoch 488/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6260 - accuracy: 0.6364
Epoch 489/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6260 - accuracy: 0.6364
Epoch 490/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6259 - accuracy: 0.6364
Epoch 491/5000

1/1 [==============================] - 0s 1ms/step - loss: 0.6259 - accuracy: 0.6364
Epoch 492/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6258 - accuracy: 0.6364
Epoch 493/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6257 - accuracy: 0.6364
Epoch 494/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6257 - accuracy: 0.6364
Epoch 495/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6256 - accuracy: 0.6364
Epoch 496/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6256 - accuracy: 0.6364
Epoch 497/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6255 - accuracy: 0.6364
Epoch 498/5000
1/1 [==============================] - 0s 3ms/step - loss: 0.6255 - accuracy: 0.6364
Epoch 499/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6254 - accuracy: 0.6364
Epoch 500/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6253 - accuracy: 0.6364
Epoch 501/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6253 - accuracy: 0.6364
Epoch 502/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6252 - accuracy: 0.6364
Epoch 503/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6252 - accuracy: 0.6364
Epoch 504/5000
1/1 [==============================] - 0s 1000us/step - loss: 0.6251 - accuracy: 0.6364
Epoch 505/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6251 - accuracy: 0.6364
Epoch 506/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6250 - accuracy: 0.6364
Epoch 507/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6250 - accuracy: 0.6364
Epoch 508/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6249 - accuracy: 0.6364
Epoch 509/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6249 - accuracy: 0.6364
Epoch 510/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6248 - accuracy: 0.6364
Epoch 511/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6247 - accuracy: 0.6364
Epoch 512/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6247 - accuracy: 0.6364
Epoch 513/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6246 - accuracy: 0.6364
Epoch 514/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6246 - accuracy: 0.6364
Epoch 515/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6245 - accuracy: 0.6364
Epoch 516/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6245 - accuracy: 0.6364
Epoch 517/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6244 - accuracy: 0.6364
Epoch 518/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6244 - accuracy: 0.6364
Epoch 519/5000
1/1 [==============================] - 0s 3ms/step - loss: 0.6243 - accuracy: 0.6818
Epoch 520/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6243 - accuracy: 0.6818
Epoch 521/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6242 - accuracy: 0.6818
Epoch 522/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6242 - accuracy: 0.6818
Epoch 523/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6241 - accuracy: 0.6818
Epoch 524/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6241 - accuracy: 0.6818
Epoch 525/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6240 - accuracy: 0.6818
Epoch 526/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6239 - accuracy: 0.6818
Epoch 527/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6239 - accuracy: 0.6818
Epoch 528/5000
1/1 [==============================] - 0s 0s/step - loss: 0.6238 - accuracy: 0.6818
Epoch 529/5000
1/1 [==============================] - 0s 1000us/step - loss: 0.6238 - accuracy: 0.6818
Epoch 530/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6237 - accuracy: 0.6818
Epoch 531/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6237 - accuracy: 0.6818
Epoch 532/5000
1/1 [==============================] - 0s 3ms/step - loss: 0.6236 - accuracy: 0.6818
Epoch 533/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6236 - accuracy: 0.6818
Epoch 534/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6235 - accuracy: 0.6818
Epoch 535/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6235 - accuracy: 0.6818
Epoch 536/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6234 - accuracy: 0.6818
Epoch 537/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6234 - accuracy: 0.6818
Epoch 538/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6233 - accuracy: 0.6818
Epoch 539/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6233 - accuracy: 0.6818
Epoch 540/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6232 - accuracy: 0.6818
Epoch 541/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6232 - accuracy: 0.6818
Epoch 542/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6231 - accuracy: 0.6818
Epoch 543/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6231 - accuracy: 0.6818
Epoch 544/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6230 - accuracy: 0.6818
Epoch 545/5000
1/1 [==============================] - 0s 0s/step - loss: 0.6230 - accuracy: 0.6818
Epoch 546/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6229 - accuracy: 0.6818
Epoch 547/5000
1/1 [==============================] - 0s 1000us/step - loss: 0.6229 - accuracy: 0.6818
Epoch 548/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6228 - accuracy: 0.6818
Epoch 549/5000
1/1 [==============================] - 0s 3ms/step - loss: 0.6227 - accuracy: 0.6818
Epoch 550/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6227 - accuracy: 0.6818
Epoch 551/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6226 - accuracy: 0.6818
Epoch 552/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6226 - accuracy: 0.6818
Epoch 553/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6225 - accuracy: 0.6818
Epoch 554/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6225 - accuracy: 0.6818
Epoch 555/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6224 - accuracy: 0.6818
Epoch 556/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6224 - accuracy: 0.6818
Epoch 557/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6223 - accuracy: 0.6818
Epoch 558/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6223 - accuracy: 0.6818
Epoch 559/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6222 - accuracy: 0.6818
Epoch 560/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6222 - accuracy: 0.6818
Epoch 561/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6221 - accuracy: 0.6818
Epoch 562/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6221 - accuracy: 0.6818
Epoch 563/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6220 - accuracy: 0.6818
Epoch 564/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6220 - accuracy: 0.6818
Epoch 565/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6219 - accuracy: 0.6818
Epoch 566/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6219 - accuracy: 0.6818
Epoch 567/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6218 - accuracy: 0.6818
Epoch 568/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6218 - accuracy: 0.6818
Epoch 569/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6217 - accuracy: 0.6818
Epoch 570/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6217 - accuracy: 0.6818
Epoch 571/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6216 - accuracy: 0.6818
Epoch 572/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6216 - accuracy: 0.6818
Epoch 573/5000

1/1 [==============================] - 0s 0s/step - loss: 0.6215 - accuracy: 0.6818
Epoch 574/5000
1/1 [==============================] - 0s 0s/step - loss: 0.6215 - accuracy: 0.6818
Epoch 575/5000
1/1 [==============================] - 0s 0s/step - loss: 0.6214 - accuracy: 0.6818
Epoch 576/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6214 - accuracy: 0.6818
Epoch 577/5000
1/1 [==============================] - 0s 1000us/step - loss: 0.6213 - accuracy: 0.6818
Epoch 578/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6213 - accuracy: 0.6818
Epoch 579/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6212 - accuracy: 0.6818
Epoch 580/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6212 - accuracy: 0.6818
Epoch 581/5000
1/1 [==============================] - 0s 3ms/step - loss: 0.6211 - accuracy: 0.6818
Epoch 582/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6211 - accuracy: 0.6818
Epoch 583/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6210 - accuracy: 0.6818
Epoch 584/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6210 - accuracy: 0.6818
Epoch 585/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6209 - accuracy: 0.6818
Epoch 586/5000
1/1 [==============================] - 0s 3ms/step - loss: 0.6209 - accuracy: 0.7273
Epoch 587/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6208 - accuracy: 0.7273
Epoch 588/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6208 - accuracy: 0.7273
Epoch 589/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6207 - accuracy: 0.7273
Epoch 590/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6207 - accuracy: 0.7273
Epoch 591/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6206 - accuracy: 0.7273
Epoch 592/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6206 - accuracy: 0.7273
Epoch 593/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6205 - accuracy: 0.7273
Epoch 594/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6205 - accuracy: 0.7273
Epoch 595/5000
1/1 [==============================] - 0s 3ms/step - loss: 0.6204 - accuracy: 0.7273
Epoch 596/5000
1/1 [==============================] - 0s 0s/step - loss: 0.6204 - accuracy: 0.7273
Epoch 597/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6203 - accuracy: 0.7273
Epoch 598/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6203 - accuracy: 0.7273
Epoch 599/5000
1/1 [==============================] - 0s 0s/step - loss: 0.6202 - accuracy: 0.7273
Epoch 600/5000
1/1 [==============================] - 0s 3ms/step - loss: 0.6202 - accuracy: 0.7273
Epoch 601/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6201 - accuracy: 0.7273
Epoch 602/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6201 - accuracy: 0.7273
Epoch 603/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6200 - accuracy: 0.7273
Epoch 604/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6200 - accuracy: 0.7273
Epoch 605/5000
1/1 [==============================] - 0s 3ms/step - loss: 0.6200 - accuracy: 0.7273
Epoch 606/5000
1/1 [==============================] - 0s 999us/step - loss: 0.6199 - accuracy: 0.7273
Epoch 607/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6199 - accuracy: 0.7273
Epoch 608/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6198 - accuracy: 0.7273
Epoch 609/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6198 - accuracy: 0.7273
Epoch 610/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6197 - accuracy: 0.7273
Epoch 611/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6197 - accuracy: 0.7273
Epoch 612/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6196 - accuracy: 0.7273
Epoch 613/5000
1/1 [==============================] - 0s 3ms/step - loss: 0.6196 - accuracy: 0.7273
Epoch 614/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6195 - accuracy: 0.7273
Epoch 615/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6195 - accuracy: 0.7273
Epoch 616/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6194 - accuracy: 0.7273
Epoch 617/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6194 - accuracy: 0.7273
Epoch 618/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6193 - accuracy: 0.7273
Epoch 619/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6193 - accuracy: 0.7273
Epoch 620/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6192 - accuracy: 0.7273
Epoch 621/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6192 - accuracy: 0.7273
Epoch 622/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6191 - accuracy: 0.7273
Epoch 623/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6191 - accuracy: 0.7273
Epoch 624/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6190 - accuracy: 0.7273
Epoch 625/5000
1/1 [==============================] - 0s 999us/step - loss: 0.6190 - accuracy: 0.7273
Epoch 626/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6189 - accuracy: 0.7273
Epoch 627/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6189 - accuracy: 0.7273
Epoch 628/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6188 - accuracy: 0.7273
Epoch 629/5000
1/1 [==============================] - 0s 3ms/step - loss: 0.6188 - accuracy: 0.7273
Epoch 630/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6187 - accuracy: 0.7273
Epoch 631/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6187 - accuracy: 0.7273
Epoch 632/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6186 - accuracy: 0.7273
Epoch 633/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6186 - accuracy: 0.7273
Epoch 634/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6185 - accuracy: 0.7273
Epoch 635/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6185 - accuracy: 0.7273
Epoch 636/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6184 - accuracy: 0.7273
Epoch 637/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6184 - accuracy: 0.7273
Epoch 638/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6183 - accuracy: 0.7273
Epoch 639/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6183 - accuracy: 0.7273
Epoch 640/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6182 - accuracy: 0.7273
Epoch 641/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6182 - accuracy: 0.7273
Epoch 642/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6181 - accuracy: 0.7273
Epoch 643/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6181 - accuracy: 0.7273
Epoch 644/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6181 - accuracy: 0.7273
Epoch 645/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6180 - accuracy: 0.7273
Epoch 646/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6180 - accuracy: 0.7273
Epoch 647/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6179 - accuracy: 0.7273
Epoch 648/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6179 - accuracy: 0.7273
Epoch 649/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6178 - accuracy: 0.7273
Epoch 650/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6178 - accuracy: 0.7273
Epoch 651/5000
1/1 [==============================] - 0s 995us/step - loss: 0.6177 - accuracy: 0.7273
Epoch 652/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6177 - accuracy: 0.7273
Epoch 653/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6176 - accuracy: 0.7273
Epoch 654/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6176 - accuracy: 0.7273
Epoch 655/5000

1/1 [==============================] - 0s 2ms/step - loss: 0.6175 - accuracy: 0.7273
Epoch 656/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6175 - accuracy: 0.7273
Epoch 657/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6174 - accuracy: 0.7273
Epoch 658/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6174 - accuracy: 0.7273
Epoch 659/5000
1/1 [==============================] - 0s 1000us/step - loss: 0.6173 - accuracy: 0.7273
Epoch 660/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6173 - accuracy: 0.7273
Epoch 661/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6172 - accuracy: 0.7273
Epoch 662/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6172 - accuracy: 0.7273
Epoch 663/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6171 - accuracy: 0.7273
Epoch 664/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6171 - accuracy: 0.7273
Epoch 665/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6170 - accuracy: 0.7273
Epoch 666/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6170 - accuracy: 0.7273
Epoch 667/5000
1/1 [==============================] - 0s 0s/step - loss: 0.6169 - accuracy: 0.7273
Epoch 668/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6169 - accuracy: 0.7273
Epoch 669/5000
1/1 [==============================] - 0s 1000us/step - loss: 0.6168 - accuracy: 0.7273
Epoch 670/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6168 - accuracy: 0.7273
Epoch 671/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6167 - accuracy: 0.7273
Epoch 672/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6167 - accuracy: 0.7273
Epoch 673/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6166 - accuracy: 0.7273
Epoch 674/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6166 - accuracy: 0.7273
Epoch 675/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6166 - accuracy: 0.7273
Epoch 676/5000
1/1 [==============================] - 0s 0s/step - loss: 0.6165 - accuracy: 0.7273
Epoch 677/5000
1/1 [==============================] - 0s 0s/step - loss: 0.6165 - accuracy: 0.7273
Epoch 678/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6164 - accuracy: 0.7273
Epoch 679/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6164 - accuracy: 0.7273
Epoch 680/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6163 - accuracy: 0.7273
Epoch 681/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6163 - accuracy: 0.7273
Epoch 682/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6162 - accuracy: 0.7273
Epoch 683/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6162 - accuracy: 0.7273
Epoch 684/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6161 - accuracy: 0.7273
Epoch 685/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6161 - accuracy: 0.7273
Epoch 686/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6160 - accuracy: 0.7273
Epoch 687/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6160 - accuracy: 0.7273
Epoch 688/5000
1/1 [==============================] - 0s 3ms/step - loss: 0.6159 - accuracy: 0.7273
Epoch 689/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6159 - accuracy: 0.7273
Epoch 690/5000
1/1 [==============================] - 0s 1000us/step - loss: 0.6158 - accuracy: 0.7273
Epoch 691/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6158 - accuracy: 0.7273
Epoch 692/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6157 - accuracy: 0.7273
Epoch 693/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6157 - accuracy: 0.7273
Epoch 694/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6156 - accuracy: 0.7273
Epoch 695/5000
1/1 [==============================] - 0s 999us/step - loss: 0.6156 - accuracy: 0.7273
Epoch 696/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6155 - accuracy: 0.7273
Epoch 697/5000
1/1 [==============================] - 0s 2ms/step - loss: 0.6155 - accuracy: 0.7273
Epoch 698/5000
1/1 [==============================] - 0s 4ms/step - loss: 0.6154 - accuracy: 0.7273
Epoch 699/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6154 - accuracy: 0.7273
Epoch 700/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6153 - accuracy: 0.7273
Epoch 701/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6153 - accuracy: 0.7273
Epoch 702/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6152 - accuracy: 0.7273
Epoch 703/5000
1/1 [==============================] - 0s 3ms/step - loss: 0.6152 - accuracy: 0.7273
Epoch 704/5000
1/1 [==============================] - 0s 1ms/step - loss: 0.6152 - accuracy: 0.7273
Epoch 705/5000
1/1 [==============================] - 0s 1000us/step - loss: 0.6151 - accuracy: 0.7273
Epoch 706/5000
1/1 [==============================] - 0s 0s/step - loss: 0.6151 - accuracy: 0.7273
Epoch 707/5000
1/1 [==============================] - ETA: 0s - loss: 0.6150 - accuracy: 0.7273

**Evaluate the model on test set**

In [14]:
model.evaluate(X_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 392ms/step - accuracy: 0.5000 - loss: 0.7108

[0.7107909321784973, 0.5]

In [15]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step

array([[0.79383534],
       [0.7450577 ],
       [0.5492765 ],
       [0.76269644],
       [0.7969307 ],
       [0.81477404]], dtype=float32)

In [16]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

**Now get the value of weights and bias from the model**

In [18]:
coef, intercept = model.get_weights()

In [19]:
coef, intercept

(array([[0.95095307],
        [0.95075333]], dtype=float32),
 array([-0.04950017], dtype=float32))

**This means w1=5.060867, w2=1.4086502, bias =-2.9137027**

In [21]:
def sigmoid(x):
        import math
        return 1 / (1 + math.exp(-x))
sigmoid(18)

0.9999999847700205

In [22]:
X_test

    age  affordibility
2    47              1
10   18              1
21   26              0
11   28              1
14   49              1
9    61              1

**Instead of model.predict, write our own prediction function that uses w1,w2 and bias**

In [24]:
def prediction_function(age, affordibility):
    weighted_sum = coef[0]*age + coef[1]*affordibility + intercept
    return sigmoid(weighted_sum)

prediction_function(.47, 1)

C:\Users\Admin\AppData\Local\Temp\ipykernel_18360\396317115.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))

0.7938353640510252

In [25]:
prediction_function(.18, 1)

C:\Users\Admin\AppData\Local\Temp\ipykernel_18360\396317115.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1 / (1 + math.exp(-x))

0.7450577437242185

**Now we start implementing gradient descent in plain python. Again the goal is to come up with same w1, w2 and bias that keras model calculated. We want to show how keras/tensorflow would have computed these values internally using gradient descent**

**First write couple of helper routines such as sigmoid and log_loss**

In [28]:
def sigmoid_numpy(X):
   return 1/(1+np.exp(-X))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

In [29]:
def log_loss(y_true, y_predicted):
    epsilon = 1e-15
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

**All right now comes the time to implement our own custom neural network class !! yay !!!**

In [31]:
class myNN:
    def __init__(self):
        self.w1 = 1 
        self.w2 = 1
        self.bias = 0
        
    def fit(self, X, y, epochs, loss_thresold):
        self.w1, self.w2, self.bias = self.gradient_descent(X['age'],X['affordibility'],y, epochs, loss_thresold)
        print(f"Final weights and bias: w1: {self.w1}, w2: {self.w2}, bias: {self.bias}")
        
    def predict(self, X_test):
        weighted_sum = self.w1*X_test['age'] + self.w2*X_test['affordibility'] + self.bias
        return sigmoid_numpy(weighted_sum)

    def gradient_descent(self, age,affordability, y_true, epochs, loss_thresold):
        w1 = w2 = 1
        bias = 0
        rate = 0.5
        n = len(age)
        for i in range(epochs):
            weighted_sum = w1 * age + w2 * affordability + bias
            y_predicted = sigmoid_numpy(weighted_sum)
            loss = log_loss(y_true, y_predicted)
            
            w1d = (1/n)*np.dot(np.transpose(age),(y_predicted-y_true)) 
            w2d = (1/n)*np.dot(np.transpose(affordability),(y_predicted-y_true)) 

            bias_d = np.mean(y_predicted-y_true)
            w1 = w1 - rate * w1d
            w2 = w2 - rate * w2d
            bias = bias - rate * bias_d
            
            if i%50==0:
                print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
            
            if loss<=loss_thresold:
                print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
                break

        return w1, w2, bias

In [32]:
customModel = myNN()
customModel.fit(X_train_scaled, y_train, epochs=8000, loss_thresold=0.4631)

Epoch:0, w1:0.974907633470177, w2:0.948348125394529, bias:-0.11341867736368583, loss:0.7113403233723417
Epoch:50, w1:1.503319554173139, w2:1.108384790367645, bias:-1.2319047301235464, loss:0.5675865113475955
Epoch:100, w1:2.2007131317600317, w2:1.2941584023238906, bias:-1.6607009122062801, loss:0.5390680417774752
Epoch:150, w1:2.8495727769689077, w2:1.369689549157275, bias:-1.986105845859897, loss:0.5176462164249294
Epoch:200, w1:3.443016970881803, w2:1.4042218624465033, bias:-2.2571369883752723, loss:0.5005011269691375
Epoch:250, w1:3.982450494649576, w2:1.4239127329321233, bias:-2.494377365971801, loss:0.48654089537617085
Epoch:300, w1:4.472179522095915, w2:1.438787986553552, bias:-2.707387811922373, loss:0.4750814640632793
Epoch:350, w1:4.917245868007634, w2:1.4525660781176122, bias:-2.901176333556766, loss:0.46561475306999006
Epoch:366, w1:5.051047623653049, w2:1.4569794548473887, bias:-2.9596534546250037, loss:0.46293944095888917
Final weights and bias: w1: 5.051047623653049, w2: 1.4569794548473887, bias: -2.9596534546250037

In [33]:
coef, intercept

(array([[0.95095307],
        [0.95075333]], dtype=float32),
 array([-0.04950017], dtype=float32))

**This shows that in the end we were able to come up with same value of w1,w2 and bias using a plain python implementation of gradient descent function**

In [35]:
X_test_scaled

     age  affordibility
2   0.47              1
10  0.18              1
21  0.26              0
11  0.28              1
14  0.49              1
9   0.61              1

**(1) Predict using custom model**

In [37]:
customModel.predict(X_test_scaled)

2     0.705020
10    0.355836
21    0.161599
11    0.477919
14    0.725586
9     0.828987
dtype: float64

**(2) Predict using tensorflow model**

In [39]:
model.predict(X_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step

array([[0.79383534],
       [0.7450577 ],
       [0.5492765 ],
       [0.76269644],
       [0.7969307 ],
       [0.81477404]], dtype=float32)

**Above you can compare predictions from our own custom model and tensoflow model. You will notice that predictions are almost same**